// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dingziran.effective.domain;

import com.dingziran.effective.domain.GoalIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GoalIntegrationTest_Roo_Configurable {
    
    declare @type: GoalIntegrationTest: @Configurable;
    
}
