// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dingziran.effective.domain;

import com.dingziran.effective.domain.Goal;
import com.dingziran.effective.domain.GoalDataOnDemand;
import com.dingziran.effective.domain.GoalIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GoalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GoalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GoalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GoalIntegrationTest: @Transactional;
    
    @Autowired
    GoalDataOnDemand GoalIntegrationTest.dod;
    
    @Test
    public void GoalIntegrationTest.testCountGoals() {
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", dod.getRandomGoal());
        long count = Goal.countGoals();
        Assert.assertTrue("Counter for 'Goal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GoalIntegrationTest.testFindGoal() {
        Goal obj = dod.getRandomGoal();
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goal' failed to provide an identifier", id);
        obj = Goal.findGoal(id);
        Assert.assertNotNull("Find method for 'Goal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Goal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GoalIntegrationTest.testFindAllGoals() {
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", dod.getRandomGoal());
        long count = Goal.countGoals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Goal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Goal> result = Goal.findAllGoals();
        Assert.assertNotNull("Find all method for 'Goal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Goal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GoalIntegrationTest.testFindGoalEntries() {
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", dod.getRandomGoal());
        long count = Goal.countGoals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Goal> result = Goal.findGoalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Goal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Goal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GoalIntegrationTest.testFlush() {
        Goal obj = dod.getRandomGoal();
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goal' failed to provide an identifier", id);
        obj = Goal.findGoal(id);
        Assert.assertNotNull("Find method for 'Goal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGoal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Goal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoalIntegrationTest.testMergeUpdate() {
        Goal obj = dod.getRandomGoal();
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goal' failed to provide an identifier", id);
        obj = Goal.findGoal(id);
        boolean modified =  dod.modifyGoal(obj);
        Integer currentVersion = obj.getVersion();
        Goal merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Goal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", dod.getRandomGoal());
        Goal obj = dod.getNewTransientGoal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Goal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Goal' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Goal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GoalIntegrationTest.testRemove() {
        Goal obj = dod.getRandomGoal();
        Assert.assertNotNull("Data on demand for 'Goal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Goal' failed to provide an identifier", id);
        obj = Goal.findGoal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Goal' with identifier '" + id + "'", Goal.findGoal(id));
    }
    
}
